# Generated by Django 6.0.4 on 2026-04-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('chief_complaint', models.CharField(max_length=300)),
                ('heart_rate', models.IntegerField()),
                ('systolic_bp', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('respiratory_rate', models.IntegerField()),
                ('gcs_score', models.IntegerField(default=15)),
                ('priority_score', models.IntegerField(default=0)),
                ('priority_level', models.CharField(default='low', max_length=20)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
    ]
